from __future__ import annotations

from utilities import Matrix
from sympy.matrices.normalforms import smith_normal_decomp
from sympy.polys.domains.domain import Domain
from sympy.polys.polyerrors import ExactQuotientFailed
from sympy.polys.domains import ZZ, QQ
from sympy.matrices.matrices import MatrixBase

_verify = True


def _is_field(domain: Domain) -> bool:
    """Return True when the domain advertises field semantics."""
    return bool(getattr(domain, "is_Field", False) or getattr(domain, "is_field", False))


def divides(a, d, domain: Domain):
    """Return True iff d divides a in the domain (fields always succeed when d != 0)."""
    d_dom = domain.convert(d)
    a_dom = domain.convert(a)
    if d_dom == domain.zero:
        # By convention 0 only divides 0.
        return a_dom == domain.zero

    # Fast path for fields: every nonzero element divides any element
    if _is_field(domain):
        return True

    try:  # try exact division
        domain.exquo(a_dom, d_dom)
        return True
    except ExactQuotientFailed:
        return False


def _hstack(domain, *args) -> "SNFMatrix":
    """
    Helper to horizontally stack column vectors/matrices and wrap as SNFMatrix.
    """
    return SNFMatrix(Matrix.hstack(*args), domain=domain)


class SNFMatrix(Matrix):
    """Matrix that caches SNF (or field rank/nullspace) for kernel/span queries."""

    def __new__(cls, *args, domain=ZZ, **kwargs) -> "SNFMatrix":
        """Build an SNFMatrix; use field rank/nullspace or PID Smith normal form."""
        if len(args) == 1 and isinstance(args[0], MatrixBase):
            # Build from its data instead of passing the matrix itself
            self = super().__new__(cls, args[0].tolist(), **kwargs)
        else:
            self = super().__new__(cls, *args, **kwargs)

        # Verify entries are coercible to domain
        if _verify:
            for entry in self:
                domain.convert(entry)

        self.domain = domain

        # Fast path when the domain is a field: avoid SNF and use rank/nullspace
        if _is_field(domain):
            # Over a field, rank is simply the matrix rank
            self.r = int(super(SNFMatrix, self).rank())  # ensure int
            return self

        # PID path: use Smith normal form
        if _verify:
            assert domain.is_PID
        self._D, self._U, self._V = smith_normal_decomp(self, domain=domain)

        # Compute rank from SNF diagonal: number of non-zero diagonal entries
        r = 0
        for i in range(min(self.rows, self.cols)):
            if self._D[i, i] != 0:
                r += 1
            else:
                break
        self.r = r
        return self

    @classmethod
    def from_columns(cls, domain: Domain, dim: int, columns) -> "SNFMatrix":
        """Build from column vectors; empty input yields a dim x 0 zero matrix."""
        columns = list(columns)
        if not columns:
            base = Matrix.zeros(dim, 0)
            return cls(base, domain=domain)

        for v in columns:
            if v.rows != dim or v.cols != 1:
                raise ValueError(
                    "All columns must be column vectors of shape (dim, 1); "
                    f"got shape ({v.rows}, {v.cols})."
                )
        base = Matrix.hstack(*columns)
        return cls(base, domain=domain)

    def get_kernel(self):
        """Return a matrix whose columns form a basis of ker(self) over the domain."""
        if _is_field(self.domain):
            # Over a field, compute kernel via nullspace
            basis = super(SNFMatrix, self).nullspace()
            if not basis:
                return Matrix.zeros(self.cols, 0)
            return Matrix.hstack(*basis)

        # Using U * A * V = D, the kernel of A is generated by the
        # columns of V corresponding to the zero diagonal entries of D.
        # If r is the rank, then indices [r, ..., n-1] span ker(A).
        if self.r == self.cols:
            # Trivial kernel: return an empty matrix with correct row size
            return Matrix.zeros(self.cols, 0)
        return self._V[:, self.r:]

    def column_spans(self, b: Matrix) -> bool:
        """Return True iff b is in the column span (rank test for fields, SNF for PIDs)."""
        assert b.cols == 1 and b.rows == self.rows
        if _is_field(self.domain):
            # Over a field, b is in the column span iff rank(A|b) == rank(A)
            A = self
            return int(A.rank()) == int(Matrix.hstack(A, b).rank())

        bprime = self._U * b

        # 1) Zero conditions on the lower block: b'_{i} = 0 for i > r
        for i in range(self.r, self.rows):
            if self.domain.convert(bprime[i, 0]) != self.domain.zero:
                return False

        # 2) Divisibility conditions on the first r coordinates: d_i | b'_i
        for i in range(self.r):
            di = self._D[i, i]
            if not divides(bprime[i, 0], di, self.domain):
                return False
        return True

    def __repr__(self):
        return f"SNFMatrix {self.tolist()}"


class Module:
    """Helper for classifying vectors in span_set modulo zero_set."""

    verify = True

    def __init__(self, domain, dim, span_set, zero_set):
        """Store generators and optionally verify zero_set within span_set."""
        self.domain, self.dim = domain, dim
        self.span_set, self.zero_set = span_set, zero_set
        self._span_matrix = SNFMatrix.from_columns(domain, dim, span_set)
        self._zero_matrix = SNFMatrix.from_columns(domain, dim, zero_set)
        if Module.verify:
            self._verify_zero_in_span()

    def _verify_zero_in_span(self):
        """Ensure each zero_set vector lies in span(span_set)."""
        for k in self.zero_set:
            if not self._span_matrix.column_spans(k):
                raise AssertionError("zero_set element not in span(span_set)")

    def classify(self, v: Matrix) -> str:
        """Return in_zero_span, in_span_not_zero, or outside_span for vector v."""
        assert v.cols == 1 and v.rows == self.dim

        if len(self.zero_set) == 0:
            # With no explicit zero-generators we interpret K = {0}.
            in_zero_span = all(self.domain.convert(v[i, 0]) == self.domain.zero for i in range(self.dim))
        else:
            in_zero_span = self._zero_matrix.column_spans(v)

        if len(self.span_set) == 0:
            # Likewise, an empty span_set defines the zero submodule.
            in_span = all(self.domain.convert(v[i, 0]) == self.domain.zero for i in range(self.dim))
        else:
            in_span = self._span_matrix.column_spans(v)

        if in_zero_span:
            return 'in_zero_span'
        if in_span:
            return 'in_span_not_zero'
        return 'outside_span'


class Differential:
    """Linear map between modules, defined on generators plus zeros."""

    verify = True

    def __init__(self, from_module: Module, to_module: Module, non_zero_info: dict | None = None):
        self.from_module = from_module
        self.to_module = to_module
        self.matrix = None
        self.non_zero_info = non_zero_info or {}

        if Differential.verify:
            assert self.from_module.domain == self.to_module.domain
        self.domain = self.from_module.domain

        # Filter out entries whose source is in K; optionally verify target in K'.
        filtered: dict = {}
        for k, v in self.non_zero_info.items():
            if Differential.verify:
                assert v.rows == self.to_module.dim and v.cols == 1
                assert self.to_module._span_matrix.column_spans(v)
            if self.from_module._zero_matrix.column_spans(k):
                if Differential.verify:
                    assert self.to_module._zero_matrix.column_spans(v)
                continue
            filtered[k] = v
        self.non_zero_info = filtered

    def _solve_coeffs(self, basis: SNFMatrix, target: Matrix) -> Matrix:
        """Find one coefficient vector c with basis * c = target."""
        if basis.cols == 0:
            return Matrix.zeros(0, 1)
        if _is_field(self.domain):
            sol, _ = basis.gauss_jordan_solve(target)
            return sol
        # PID path via SNF
        U, D, V = basis._U, basis._D, basis._V
        r = basis.r
        bprime = U * target
        y = Matrix.zeros(basis.cols, 1)
        for i in range(r):
            di = D[i, i]
            y[i, 0] = self.domain.exquo(bprime[i, 0], di)
        x = V * y
        return x

    def _basis_and_redundancy(self, vectors: list[Matrix]):
        """Return independent subset, their indices, and representations for redundant ones."""
        basis_vecs: list[Matrix] = []
        basis_indices: list[int] = []
        reprs: dict[int, Matrix] = {}
        basis_mat = SNFMatrix.from_columns(self.domain, self.from_module.dim, [])

        for idx, v in enumerate(vectors):
            if basis_mat.cols > 0 and basis_mat.column_spans(v):
                coeffs = self._solve_coeffs(basis_mat, v)
                reprs[idx] = coeffs
                continue
            basis_vecs.append(v)
            basis_indices.append(idx)
            basis_mat = SNFMatrix.from_columns(self.domain, self.from_module.dim, basis_vecs)
        return basis_vecs, basis_indices, reprs

    def compute_matrix(self) -> bool:
        """
        Build the differential matrix if generators suffice.

        Returns False if non_zero_info together with K does not span S.
        On success, sets self.matrix (m' x m) and prunes redundant generators.
        """
        zero_set = list(self.from_module.zero_set)
        key_list = list(self.non_zero_info.keys())
        combined = zero_set + key_list

        # Do the keys ∪ K span S?
        generator_mat = SNFMatrix.from_columns(self.domain, self.from_module.dim, combined)
        for v in self.from_module.span_set:
            if not generator_mat.column_spans(v):
                return False

        # Extract a basis and record representations of redundant generators.
        basis_vecs, basis_indices, reprs = self._basis_and_redundancy(combined)
        basis_mat = SNFMatrix.from_columns(self.domain, self.from_module.dim, basis_vecs)

        # Build images for basis vectors.
        images_basis: list[Matrix] = []
        for idx in basis_indices:
            if idx < len(zero_set):
                images_basis.append(Matrix.zeros(self.to_module.dim, 1))
            else:
                key = key_list[idx - len(zero_set)]
                images_basis.append(self.non_zero_info[key])

        # Verify redundant images if requested.
        if Differential.verify:
            for idx, coeffs in reprs.items():
                img = Matrix.zeros(self.to_module.dim, 1)
                for j, c in enumerate(coeffs):
                    if c != 0:
                        img += images_basis[j] * c
                if idx < len(zero_set):
                    expected = Matrix.zeros(self.to_module.dim, 1)
                else:
                    key = key_list[idx - len(zero_set)]
                    expected = self.non_zero_info[key]
                assert img == expected

        # Compute matrix columns so that M * basis_vec = images_basis.
        m_rows = self.to_module.dim
        m_cols = self.from_module.dim
        result = Matrix.zeros(m_rows, m_cols)
        for j in range(m_cols):
            e = Matrix.zeros(m_cols, 1)
            e[j, 0] = self.domain.one if hasattr(self.domain, "one") else 1
            if basis_mat.column_spans(e):
                coeffs = self._solve_coeffs(basis_mat, e)
                col_img = Matrix.zeros(m_rows, 1)
                for k, c in enumerate(coeffs):
                    if c != 0:
                        col_img += images_basis[k] * c
                result[:, j] = col_img
            else:
                # Outside S; map to zero
                result[:, j] = Matrix.zeros(m_rows, 1)

        # Prune generators to the basis
        self.from_module.zero_set = [zero_set[i] for i in basis_indices if i < len(zero_set)]
        new_info = {}
        for idx in basis_indices:
            if idx >= len(zero_set):
                key = key_list[idx - len(zero_set)]
                new_info[key] = self.non_zero_info[key]
        self.non_zero_info = new_info

        self.matrix = result
        return True
    


if __name__ == "__main__":
    # Basic smoke tests for SNFMatrix over ZZ
    print("=== Testing SNFMatrix over ZZ ===")
    a = SNFMatrix([[1, 1], [1, 1]])
    print("Matrix a:", a)
    print("Rank r:", a.r)
    print("Kernel basis (columns):")
    print(a.get_kernel())
    print("Does (1, 2)^T lie in the column span of a?")
    print(a.column_spans(Matrix([[1], [2]])))
    print()

    # Same matrix, but over a field (QQ) – exercises the field code path
    print("=== Testing SNFMatrix over QQ ===")
    a_Q = SNFMatrix([[1, 1], [1, 1]], domain=QQ)
    print("Matrix a_Q:", a_Q)
    print("Rank r over QQ:", a_Q.r)
    print("Kernel over QQ:")
    print(a_Q.get_kernel())
    print()

    # Test SNFMatrix from_columns helper
    print("=== Testing SNFMatrix.from_columns ===")
    v1 = Matrix([[1], [2]])
    v2 = Matrix([[3], [4]])
    span_mat = SNFMatrix.from_columns(ZZ, 2, [v1, v2])
    print("Span matrix built from columns:")
    print(span_mat)
    print("Kernel of span_mat:")
    print(span_mat.get_kernel())
    print()

    # Module tests: zero_set contained in span_set
    print("=== Testing Module classification ===")
    m = Module(
        ZZ, 2,
        [Matrix([[1], [2]]), Matrix([[1], [2]])],
        [Matrix([[1], [4]])]
    )
    test_vecs = [
        Matrix([[0], [0]]),
        Matrix([[1], [4]]),
        Matrix([[2], [4]]),
        Matrix([[1], [0]]),
    ]
    for vec in test_vecs:
        print(f"v = {vec.tolist()} ->", m.classify(vec))

    # A module with empty zero_set and non-trivial span_set
    print("\n=== Testing Module with empty zero_set ===")
    m2 = Module(ZZ, 2, [Matrix([[1], [0]]), Matrix([[0], [1]])], [])
    for vec in test_vecs:
        print(f"v = {vec.tolist()} ->", m2.classify(vec))
